// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-txtC7kdRlJUwfQLdaljcW8JieEvYWs',
    appId: '1:693536509818:web:e78d01049986a49fc150c3',
    messagingSenderId: '693536509818',
    projectId: 'ubser-d502c',
    authDomain: 'ubser-d502c.firebaseapp.com',
    storageBucket: 'ubser-d502c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6fUWVjNdR24vp9QxlNLH5dkTEI--K8k',
    appId: '1:693536509818:android:e9ebd0f8d62ec9cdc150c3',
    messagingSenderId: '693536509818',
    projectId: 'ubser-d502c',
    storageBucket: 'ubser-d502c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hw-IhdmiCWNQLUuZaoIC_7UcIVrVXqA',
    appId: '1:693536509818:ios:c45d8eb1f485bd64c150c3',
    messagingSenderId: '693536509818',
    projectId: 'ubser-d502c',
    storageBucket: 'ubser-d502c.firebasestorage.app',
    iosBundleId: 'com.example.abser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hw-IhdmiCWNQLUuZaoIC_7UcIVrVXqA',
    appId: '1:693536509818:ios:c45d8eb1f485bd64c150c3',
    messagingSenderId: '693536509818',
    projectId: 'ubser-d502c',
    storageBucket: 'ubser-d502c.firebasestorage.app',
    iosBundleId: 'com.example.abser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-txtC7kdRlJUwfQLdaljcW8JieEvYWs',
    appId: '1:693536509818:web:a4f9a6bb0fc0e2d3c150c3',
    messagingSenderId: '693536509818',
    projectId: 'ubser-d502c',
    authDomain: 'ubser-d502c.firebaseapp.com',
    storageBucket: 'ubser-d502c.firebasestorage.app',
  );
}
